# Generated by Django 2.0.7 on 2018-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
            ],
        ),
    ]
