# Generated by Django 2.1 on 2018-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
