# Generated by Django 2.0.7 on 2018-08-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0003_auto_20180814_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='post_count',
            field=models.IntegerField(default=1),
        ),
    ]
