# Generated by Django 2.0.7 on 2018-08-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0004_forumthread_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumthread',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
