# Generated by Django 2.0.7 on 2018-08-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0005_auto_20180818_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
