# Generated by Django 2.0.7 on 2018-08-18 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0006_auto_20180818_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
