# Generated by Django 2.0.7 on 2018-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0007_auto_20180818_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
