# Generated by Django 2.0.7 on 2018-08-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0009_auto_20180818_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='date',
        ),
    ]
