# Generated by Django 2.0.7 on 2018-08-18 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('denouement', '0010_auto_20180818_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumthread',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
